import { test } from 'node:test';
import assert from 'node:assert/strict';
import { currencies,currencyDigits,decimalToUnits,findCurrencies } from '../lib/currencies';
import { billSchema,changeCurrency,money,sampleBill,shares,total } from '../lib/bill';
import { canEditRoom,editRoom,secretDigest } from '../lib/edit-room';
import { contactFromText,mergeContacts } from '../lib/contacts';
import type { Room } from '../lib/rooms';

test('catalog includes KZT by country, code and local symbol',()=>{assert.ok(currencies.length>170);for(const q of ['Kazakhstan','KZT','₸','тенге'])assert.ok(findCurrencies(q).some(c=>c.code==='KZT'));});
test('zero- and three-decimal currencies conserve amounts and USDC cents',()=>{for(const currency of ['KZT','JPY','KWD']){let b=sampleBill();b={...b,...changeCurrency(b,currency)};b.rate=.00225;assert.equal(b.precision,currencyDigits(currency));assert.equal(total(b)/10**b.precision,96);const parts=shares(b);assert.equal(parts.reduce((n,p)=>n+p.amount,0),total(b));assert.equal(parts.reduce((n,p)=>n+p.usdc,0),22);}assert.equal(decimalToUnits('1,234',3),1234);assert.match(money(1234,'KWD',3),/1\.234/);});
test('legacy bills retain their original two-decimal representation',()=>{const {precision,...legacy}=sampleBill();assert.equal(billSchema.parse({...legacy,currency:'JPY'}).precision,2);});
test('friend emails are validated, normalized and remembered without duplicates',()=>{const c=contactFromText('Sam.Example@EXAMPLE.COM');assert.equal(c.email,'sam.example@example.com');assert.equal(c.name,'sam example');assert.equal(mergeContacts([c],[{...c,name:'Sam',lastUsed:(c.lastUsed||0)+1}]).length,1);assert.throws(()=>contactFromText('not@valid'));});
test('public shared links cannot edit receipts; organizer and editor can',()=>{const editToken='a'.repeat(64),b=sampleBill();const room:Room={bill:b,version:4,proofs:[],hasPhoto:false,accessHash:'b'.repeat(64),editorHash:secretDigest(editToken),ownerUid:'owner'};assert.equal(canEditRoom(room),false);assert.equal(canEditRoom(room,'someone-else'),false);assert.equal(canEditRoom(room,undefined,'c'.repeat(64)),false);assert.equal(canEditRoom(room,'owner'),true);assert.throws(()=>editRoom(room,b,4),/Only the organizer/);assert.throws(()=>editRoom(room,b,3,undefined,editToken),/Friends changed/);const updated=editRoom(room,{...b,title:'Edited'},4,undefined,editToken);assert.equal(updated.bill.title,'Edited');assert.equal(updated.bill.createdAt,b.createdAt);});
test('organizer edits keep proof and require renewed verification',()=>{const b=sampleBill(),room:Room={bill:b,version:1,proofs:[{id:'proof',personId:'mia',method:'base',reference:'test',amount:100,createdAt:1,status:'verified',message:'verified'}],hasPhoto:true,photoPath:'private.jpg',accessHash:'a'.repeat(64),ownerUid:'owner'};const updated=editRoom(room,b,1,'owner');assert.equal(updated.photoPath,'private.jpg');assert.equal(updated.proofs[0].status,'unverified');assert.equal(updated.proofs[0].reference,'test');assert.throws(()=>editRoom(room,{...b,people:b.people.filter(p=>p.id!=='mia')},1,'owner'),/Keep friends/);});
