'use client';
import { useEffect, useId, useRef, useState } from 'react';
type Option={value:string;label:string;detail?:string};
export function Autocomplete({label,value,onChange,options,onSelect,placeholder,autoFocus=false,onSubmit,onClose}:{label:string;value:string;onChange:(v:string)=>void;options:Option[];onSelect:(v:string)=>void;placeholder?:string;autoFocus?:boolean;onSubmit?:()=>void;onClose?:()=>void}){
 const id=useId(),input=useRef<HTMLInputElement>(null),[open,setOpen]=useState(false),[active,setActive]=useState(-1);
 useEffect(()=>{if(autoFocus)input.current?.focus();},[autoFocus]);
 useEffect(()=>setActive(-1),[value]);
 useEffect(()=>{if(active>=0)document.getElementById(`${id}-${active}`)?.scrollIntoView({block:'nearest'});},[active,id]);
 function select(index:number){const option=options[index];if(option){onSelect(option.value);setOpen(false);setActive(-1);}}
 return <div className="autocomplete"><input ref={input} role="combobox" aria-label={label} aria-autocomplete="list" aria-expanded={open&&options.length>0} aria-controls={`${id}-list`} aria-activedescendant={open&&active>=0?`${id}-${active}`:undefined} autoComplete="off" value={value} placeholder={placeholder} onFocus={()=>setOpen(true)} onBlur={()=>{setOpen(false);setActive(-1);onClose?.();}} onChange={e=>{onChange(e.target.value);setOpen(true);}} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);setActive(i=>Math.max(0,Math.min(options.length-1,i+(e.key==='ArrowDown'?1:-1))));}else if(e.key==='Escape'){setOpen(false);setActive(-1);onClose?.();}else if(e.key==='Enter'){if(open&&active>=0){e.preventDefault();select(active);}else if(onSubmit){e.preventDefault();onSubmit();}}else if(open&&active>=0&&options.length>0&&e.key==='Home'){e.preventDefault();setActive(0);}else if(open&&active>=0&&options.length>0&&e.key==='End'){e.preventDefault();setActive(options.length-1);}}}/>{open&&options.length>0&&<ul id={`${id}-list`} role="listbox" aria-label={`${label} suggestions`}>{options.map((option,i)=><li id={`${id}-${i}`} key={option.value} role="option" aria-selected={i===active} onMouseDown={e=>e.preventDefault()} onClick={()=>select(i)} className={i===active?'active':''}><strong>{option.label}</strong>{option.detail&&<small>{option.detail}</small>}</li>)}</ul>}</div>;
}
