'use client';
import { useEffect, useState } from 'react';
import { Bill, money } from '@/lib/bill';
import { Group } from '@/lib/group';
type Props={bill:Bill;token:string;onUpdate:(bill:Bill,group:Group)=>void};
export function GroupPanel({bill,token,onUpdate}:Props){
  const [name,setName]=useState(''),[personId,setPersonId]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{try{setPersonId(localStorage.getItem(`tabby-me:${token}`)||'');}catch{}},[token]);
  function identify(id:string){setPersonId(id);try{localStorage.setItem(`tabby-me:${token}`,id);}catch{}}
  async function update(body:Record<string,unknown>){setBusy(true);setMessage('');try{const response=await fetch('/api/group',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,...body})});const data=await response.json();if(!response.ok)throw new Error(data.error);onUpdate(data.bill,data.group);setMessage('Changes saved.');return true;}catch(e){setMessage(e instanceof Error?e.message:'Could not save. Please try again.');return false;}finally{setBusy(false);}}
  const person=bill.people.find(p=>p.id===personId);
  return <section className="panel group-panel"><div className="panel-heading"><div><h2>Join this bill</h2><p>Add yourself or choose your name below.</p></div></div><form className="add-friend" onSubmit={async e=>{e.preventDefault();const id=crypto.randomUUID();if(await update({action:'join',person:{id,name:name.trim()}})){identify(id);setName('');}}}><input aria-label="Your name" placeholder="Your name" value={name} maxLength={40} onChange={e=>setName(e.target.value)} disabled={busy}/><button className="button dark" disabled={!name.trim()||busy||bill.people.length>=20}>Join</button></form><label>Already added?<select aria-label="Your name on this bill" value={person?.id||''} onChange={e=>identify(e.target.value)} disabled={busy}><option value="">Choose your name</option>{bill.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{person&&bill.mode==='items'&&<div className="contribution-items"><h3>What did you have, {person.name}?</h3><p className="muted">Select items to contribute to. Shared items are divided among the names shown.</p>{bill.items.map(item=><label className="contribution-item" key={item.id}><input type="checkbox" aria-label={`Contribute to ${item.name}`} disabled={busy} checked={item.people.includes(person.id)} onChange={e=>{const ids=bill.items.filter(i=>i.people.includes(person.id)).map(i=>i.id);void update({action:'items',personId:person.id,itemIds:e.target.checked?[...ids,item.id]:ids.filter(id=>id!==item.id)});}}/><span><strong>{item.name}</strong><small>{money(item.amount,bill.currency,bill.precision)} · {bill.people.filter(p=>item.people.includes(p.id)).map(p=>p.name).join(', ')}</small></span></label>)}</div>}{person&&bill.mode==='equal'&&<p className="muted">This bill is split equally. Your share updates automatically when friends join.</p>}{(busy||message)&&<p className="group-message" role="status">{busy?'Saving your changes…':message}</p>}<p className="subtle">Anyone with this link can join, choose a name, and update contributions.</p></section>;
}
