'use client';
import { useState } from 'react';
import { Bill, networkNames } from '@/lib/bill';
import { Group, Proof, proofAmountChanged } from '@/lib/group';
export function ProofForm({token,personId,method,amount,initialReference='',onUpdate}:{token:string;personId:string;method:Proof['method'];amount:number;initialReference?:string;onUpdate:(bill:Bill,group:Group)=>void}){
  const [reference,setReference]=useState(initialReference),[attempt,setAttempt]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[id,setId]=useState(()=>crypto.randomUUID());
  async function save(){setBusy(true);setMessage('Saving proof…');try{const response=await fetch('/api/proof',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,id,personId,method,reference,expectedAmount:amount,verify:attempt})});const data=await response.json();if(!response.ok)throw new Error(data.error);onUpdate(data.bill,data.group);setMessage(data.proof.message);setId(crypto.randomUUID());setReference('');}catch(e){setMessage(e instanceof Error?e.message:'Could not save the proof. Please retry.');}finally{setBusy(false);}}
  if(!token.startsWith('live.'))return <p className="muted">This older split is read-only. Ask the organizer to create a new link to save proof for everyone.</p>;
  return <div className="proof-form"><h3>Already paid? Add proof</h3><label>Receipt link or transaction hash<input aria-label="Payment proof" type="text" value={reference} maxLength={2000} onChange={e=>{setReference(e.target.value);setId(crypto.randomUUID());}} placeholder="https://… or paste a hash" disabled={busy}/></label><label className="review-checkbox"><input type="checkbox" checked={attempt} onChange={e=>setAttempt(e.target.checked)} disabled={busy}/><span>Try to verify it too (optional)</span></label><p className="subtle">Proof is saved first, even if verification fails. {method==='paypal'?'PayPal needs confirmation from the recipient.':''}</p><button className="button full-width" disabled={!reference.trim()||busy} onClick={save}>{busy?'Saving proof…':'Save payment proof'}</button>{message&&<p className="group-message" role="status">{message}</p>}</div>;
}
export function ProofList({bill,group}:{bill:Bill;group:Group}){
  return <section className="panel proof-list"><h2>Payment proofs</h2><p className="muted">A saved receipt is separate from a verified payment.</p>{!group.proofs.length?<p className="muted">No proof added yet. Choose Pay share to add a receipt link or hash.</p>:group.proofs.map(p=><article className="proof-entry" key={p.id}><strong>{bill.people.find(person=>person.id===p.personId)?.name} · {p.method==='paypal'?'PayPal':networkNames[p.method]}</strong><span className={`proof-status ${p.status}`}>{p.status==='verified'?'Verified':p.status==='failed'?'Saved · verification failed':'Saved · unverified'}</span><p>{(p.amount/100).toFixed(2)} {p.method==='paypal'?'USD':'USDC'} · {new Date(p.createdAt).toLocaleString()}</p>{/^https?:\/\//i.test(p.reference)?<a href={p.reference} target="_blank" rel="noreferrer">Open receipt link ↗</a>:<code>{p.reference}</code>}<p>{p.message}</p>{proofAmountChanged(p,bill)&&<p className="proof-changed">The share changed after this proof was submitted. Review the remaining amount with your friend.</p>}</article>)}</section>;
}
